sudo: false

branches:
  - master

os:
  - linux

compiler:
  - gcc

services:
  - docker

before_script:
  - docker pull ebassi/flathub:gnome-3.24
  - echo FROM ebassi/flathub:gnome-3.24 > Dockerfile
  - echo ENV FLATPAK_OSTREE_REPO_MODE=user-only >> Dockerfile
  - echo RUN flatpak install gnome org.freedesktop.Platform//1.6 >> Dockerfile
  - echo ADD . /root/endless-sdk-flatpak >> Dockerfile
  - docker build -t endless-ci .

script:
  - docker run --device=/dev/fuse:/dev/fuse --privileged -t ebassi/endless-ci:sdk-build /root/endless-sdk-flatpak/endless-sdk-build.sh

after_success:
  - if [[ -n "$DOCKER_USERNAME" && "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" ;
      docker push push ebassi/endless-sdk:latest ;
    fi
