sudo: false

branches:
  - master

os:
  - linux

services:
  - docker

before_script:
  - docker pull ebassi/endlessci:validate
  - echo FROM ebassi/endlessci:validate > Dockerfile
  - echo ADD . /root >> Dockerfile
  - docker build -t endlessci .

script:
  - docker run -t endlessci make -C /root check
