sudo: false

branches:
  - master
  - /^sdk-\d+$

os:
  - linux

services:
  - docker

# We use the same Docker image as freedesktop-sdk:
# <https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/19.08/.gitlab-ci.yml>

env:
  global:
    - IMAGE_ID: 'f280b874c49cee3ce2e5f3c4af1495238e134e3c'
    - DOCKER_REGISTRY: "registry.gitlab.com/freedesktop-sdk/infrastructure/freedesktop-sdk-docker-images"
    - DOCKER_AMD64: "${DOCKER_REGISTRY}/bst14/amd64:${IMAGE_ID}"
    - DOCKER_AARCH64: "${DOCKER_REGISTRY}/bst14/arm64:${IMAGE_ID}"
  jobs:
    - ARCH=x86_64
    - ARCH=arm
    - ARCH=aarch64

before_script:
  - docker pull ${DOCKER_AMD64}
  - echo "FROM ${DOCKER_AMD64}" > Dockerfile
  - echo "ADD . /endless-sdk-flatpak" >> Dockerfile
  - docker build -t local-endless-sdk-ci .

script:
  - docker run --privileged -t local-endless-sdk-ci make -C /endless-sdk-flatpak ARCH="${ARCH}" BOOTSTRAP_ARCH="${ARCH}" check-format
