#!/bin/sh

cat <<EOF > Makefile
all:

install:
	mkdir -p ${DESTDIR}/usr/lib
	install os-release ${DESTDIR}/usr/lib
	mkdir -p ${DESTDIR}/usr/share/appdata
	mkdir -p ${DESTDIR}/etc
	install issue ${DESTDIR}/etc
	install issue.net ${DESTDIR}/etc
	install com.endlessm.apps.Platform.appdata.xml ${DESTDIR}/usr/share/appdata
	install com.endlessm.apps.Sdk.appdata.xml ${DESTDIR}/usr/share/appdata
	appstream-compose --basename=com.endlessm.apps.Platform --prefix=/usr --origin=flatpak com.endlessm.apps.Platform
	appstream-compose --basename=com.endlessm.apps.Sdk --prefix=/usr --origin=flatpak com.endlessm.apps.Sdk
EOF
