kind: stack

depends:
- tests/sdk/basin.bst
- tests/sdk-build-depends/hotdoc-modular-framework.bst
- tests/sdk-depends/emeus.bst
- tests/sdk-depends/eos-knowledge-content-renderer.bst
- tests/sdk-depends/eos-shard.bst
- tests/sdk-depends/maxwell.bst
- tests/sdk-depends/xapian-glib.bst
# - tests/sdk/eos-knowledge-lib.bst
# - tests/sdk/eos-metrics.bst
- tests/sdk/eos-sdk.bst
- tests/sdk/libdmodel.bst
